### ISSUE TITLE
Support for AndroidX ?

### ISSUE THREAD

**Issue by MartyCatawiki** [square/RxIdler#17]
Is there a time-plan for supporting AndroidX espresso testing?

**Comment by mrk-han** [comment]
@MartyCatawiki Have you tried using with AndroidX yet? If updating this to support AndroidX, will it still function for ATSL?

**Comment by MartyCatawiki** [comment]
@mrk-han Sorry no, we had too many issues with our own project during migrating it to AndroidX

**Comment by felipehjcosta** [comment]
My project uses AndroidX and worked fine. I take the opportunity to open a PR to [migrate to AndroidX](#19)

**Comment by jrodbx** [comment]
https://github.com/square/RxIdler/pull/19
