### ISSUE TITLE
Is there any idler library used for rxjava3?

### ISSUE THREAD

**Issue by Yunze-Li** [square/RxIdler#30]
Hi,

Currently I'm working on migration to rxjava3. In our project we are using this idler to testing with Espresso, but after migrated to rxjava3, how can we using Idler? Thanks for help.

**Comment by laalto** [comment]
For what it's worth, I made a quick port of rx2-idler to rxjava3. https://github.com/laalto/RxIdler/commit/75af51ce8be7d9298711ba2b39d2bce58404f9a1
